/**
 * PLZ (postal code) to city lookup for Switzerland, Liechtenstein, Austria, and Germany
 */

export interface PlzEntry {
  city: string;
  country: string;
}

const PLZ_DATABASE: Record<string, PlzEntry> = {
  // Liechtenstein (all postal codes)
  "9485": { city: "Nendeln", country: "LI" },
  "9486": { city: "Schaanwald", country: "LI" },
  "9487": { city: "Gamprin-Bendern", country: "LI" },
  "9488": { city: "Schellenberg", country: "LI" },
  "9489": { city: "Schaan", country: "LI" },
  "9490": { city: "Vaduz", country: "LI" },
  "9491": { city: "Ruggell", country: "LI" },
  "9492": { city: "Eschen", country: "LI" },
  "9493": { city: "Mauren", country: "LI" },
  "9494": { city: "Schaan", country: "LI" },
  "9495": { city: "Triesen", country: "LI" },
  "9496": { city: "Balzers", country: "LI" },
  "9497": { city: "Triesenberg", country: "LI" },
  "9498": { city: "Planken", country: "LI" },
  // Malbun area
  "9497 Malbun": { city: "Malbun", country: "LI" },

  // Switzerland - Major cities and ski resorts
  "8001": { city: "Zürich", country: "CH" },
  "8002": { city: "Zürich", country: "CH" },
  "8003": { city: "Zürich", country: "CH" },
  "8004": { city: "Zürich", country: "CH" },
  "8005": { city: "Zürich", country: "CH" },
  "8006": { city: "Zürich", country: "CH" },
  "8008": { city: "Zürich", country: "CH" },
  "8032": { city: "Zürich", country: "CH" },
  "8037": { city: "Zürich", country: "CH" },
  "8038": { city: "Zürich", country: "CH" },
  "8041": { city: "Zürich", country: "CH" },
  "8044": { city: "Zürich", country: "CH" },
  "8045": { city: "Zürich", country: "CH" },
  "8046": { city: "Zürich", country: "CH" },
  "8047": { city: "Zürich", country: "CH" },
  "8048": { city: "Zürich", country: "CH" },
  "8049": { city: "Zürich", country: "CH" },
  "8050": { city: "Zürich", country: "CH" },
  "8051": { city: "Zürich", country: "CH" },
  "8052": { city: "Zürich", country: "CH" },
  "8053": { city: "Zürich", country: "CH" },
  "8055": { city: "Zürich", country: "CH" },
  "8057": { city: "Zürich", country: "CH" },
  "3000": { city: "Bern", country: "CH" },
  "3001": { city: "Bern", country: "CH" },
  "3004": { city: "Bern", country: "CH" },
  "3005": { city: "Bern", country: "CH" },
  "3006": { city: "Bern", country: "CH" },
  "3007": { city: "Bern", country: "CH" },
  "3008": { city: "Bern", country: "CH" },
  "3010": { city: "Bern", country: "CH" },
  "3011": { city: "Bern", country: "CH" },
  "3012": { city: "Bern", country: "CH" },
  "3013": { city: "Bern", country: "CH" },
  "3014": { city: "Bern", country: "CH" },
  "3015": { city: "Bern", country: "CH" },
  "4000": { city: "Basel", country: "CH" },
  "4001": { city: "Basel", country: "CH" },
  "4051": { city: "Basel", country: "CH" },
  "4052": { city: "Basel", country: "CH" },
  "4053": { city: "Basel", country: "CH" },
  "4054": { city: "Basel", country: "CH" },
  "4055": { city: "Basel", country: "CH" },
  "4056": { city: "Basel", country: "CH" },
  "4057": { city: "Basel", country: "CH" },
  "4058": { city: "Basel", country: "CH" },
  "1200": { city: "Genève", country: "CH" },
  "1201": { city: "Genève", country: "CH" },
  "1202": { city: "Genève", country: "CH" },
  "1203": { city: "Genève", country: "CH" },
  "1204": { city: "Genève", country: "CH" },
  "1205": { city: "Genève", country: "CH" },
  "1206": { city: "Genève", country: "CH" },
  "1207": { city: "Genève", country: "CH" },
  "1208": { city: "Genève", country: "CH" },
  "1209": { city: "Genève", country: "CH" },
  "6900": { city: "Lugano", country: "CH" },
  "6901": { city: "Lugano", country: "CH" },
  "6902": { city: "Lugano", country: "CH" },
  "6903": { city: "Lugano", country: "CH" },
  "9000": { city: "St. Gallen", country: "CH" },
  "9001": { city: "St. Gallen", country: "CH" },
  "9004": { city: "St. Gallen", country: "CH" },
  "9006": { city: "St. Gallen", country: "CH" },
  "9007": { city: "St. Gallen", country: "CH" },
  "9008": { city: "St. Gallen", country: "CH" },
  "9010": { city: "St. Gallen", country: "CH" },
  "9011": { city: "St. Gallen", country: "CH" },
  "9012": { city: "St. Gallen", country: "CH" },
  "9014": { city: "St. Gallen", country: "CH" },
  "9015": { city: "St. Gallen", country: "CH" },
  "9016": { city: "St. Gallen", country: "CH" },
  "7000": { city: "Chur", country: "CH" },
  "7001": { city: "Chur", country: "CH" },
  "7002": { city: "Chur", country: "CH" },
  "7004": { city: "Chur", country: "CH" },
  "7007": { city: "Chur", country: "CH" },
  // Ski resorts
  "7500": { city: "St. Moritz", country: "CH" },
  "7270": { city: "Davos Platz", country: "CH" },
  "7260": { city: "Davos Dorf", country: "CH" },
  "3920": { city: "Zermatt", country: "CH" },
  "6390": { city: "Engelberg", country: "CH" },
  "3800": { city: "Interlaken", country: "CH" },
  "3818": { city: "Grindelwald", country: "CH" },
  "3823": { city: "Wengen", country: "CH" },
  "3825": { city: "Mürren", country: "CH" },
  "3780": { city: "Gstaad", country: "CH" },
  "3906": { city: "Saas-Fee", country: "CH" },
  "1936": { city: "Verbier", country: "CH" },
  "3963": { city: "Crans-Montana", country: "CH" },
  "7050": { city: "Arosa", country: "CH" },
  "7250": { city: "Klosters", country: "CH" },
  "7017": { city: "Flims Dorf", country: "CH" },
  "7018": { city: "Flims Waldhaus", country: "CH" },
  "7031": { city: "Laax", country: "CH" },
  "7032": { city: "Laax GR", country: "CH" },
  "7514": { city: "Ftan", country: "CH" },
  "7550": { city: "Scuol", country: "CH" },
  "7563": { city: "Samnaun", country: "CH" },
  "6460": { city: "Altdorf", country: "CH" },
  "6490": { city: "Andermatt", country: "CH" },
  // Near Liechtenstein
  "9470": { city: "Buchs SG", country: "CH" },
  "9471": { city: "Buchs SG", country: "CH" },
  "9472": { city: "Grabs", country: "CH" },
  "9473": { city: "Gams", country: "CH" },
  "9475": { city: "Sevelen", country: "CH" },
  "9476": { city: "Weite", country: "CH" },
  "9477": { city: "Trübbach", country: "CH" },
  "9478": { city: "Azmoos", country: "CH" },
  "9479": { city: "Oberschan", country: "CH" },
  "9450": { city: "Altstätten", country: "CH" },
  "9451": { city: "Kriessern", country: "CH" },
  "9452": { city: "Hinterforst", country: "CH" },
  "9453": { city: "Eichberg", country: "CH" },
  "9463": { city: "Oberriet SG", country: "CH" },
  "9464": { city: "Rüthi SG", country: "CH" },
  "9466": { city: "Sennwald", country: "CH" },
  "9467": { city: "Frümsen", country: "CH" },
  "9468": { city: "Sax", country: "CH" },
  "9469": { city: "Haag SG", country: "CH" },
  // Lucerne region
  "6000": { city: "Luzern", country: "CH" },
  "6002": { city: "Luzern", country: "CH" },
  "6003": { city: "Luzern", country: "CH" },
  "6004": { city: "Luzern", country: "CH" },
  "6005": { city: "Luzern", country: "CH" },
  "6006": { city: "Luzern", country: "CH" },
  "6010": { city: "Kriens", country: "CH" },
  "6014": { city: "Luzern", country: "CH" },
  // Winterthur
  "8400": { city: "Winterthur", country: "CH" },
  "8401": { city: "Winterthur", country: "CH" },
  "8402": { city: "Winterthur", country: "CH" },
  "8404": { city: "Winterthur", country: "CH" },
  "8405": { city: "Winterthur", country: "CH" },
  "8406": { city: "Winterthur", country: "CH" },
  "8408": { city: "Winterthur", country: "CH" },
  "8409": { city: "Winterthur", country: "CH" },

  // Austria - Vorarlberg (closest to Liechtenstein)
  "6800": { city: "Feldkirch", country: "AT" },
  "6805": { city: "Feldkirch-Gisingen", country: "AT" },
  "6806": { city: "Feldkirch-Nofels", country: "AT" },
  "6807": { city: "Feldkirch-Tosters", country: "AT" },
  "6808": { city: "Feldkirch-Levis", country: "AT" },
  "6811": { city: "Göfis", country: "AT" },
  "6812": { city: "Meiningen", country: "AT" },
  "6820": { city: "Frastanz", country: "AT" },
  "6822": { city: "Satteins", country: "AT" },
  "6824": { city: "Schlins", country: "AT" },
  "6830": { city: "Rankweil", country: "AT" },
  "6832": { city: "Sulz", country: "AT" },
  "6833": { city: "Klaus", country: "AT" },
  "6834": { city: "Röthis", country: "AT" },
  "6840": { city: "Götzis", country: "AT" },
  "6841": { city: "Mäder", country: "AT" },
  "6842": { city: "Koblach", country: "AT" },
  "6844": { city: "Altach", country: "AT" },
  "6845": { city: "Hohenems", country: "AT" },
  "6850": { city: "Dornbirn", country: "AT" },
  "6851": { city: "Dornbirn", country: "AT" },
  "6856": { city: "Schwarzach", country: "AT" },
  "6858": { city: "Bildstein", country: "AT" },
  "6861": { city: "Alberschwende", country: "AT" },
  "6863": { city: "Egg", country: "AT" },
  "6870": { city: "Bezau", country: "AT" },
  "6890": { city: "Lustenau", country: "AT" },
  // Note: 6900 conflicts with Lugano CH, using Bregenz with suffix
  "6911": { city: "Lochau", country: "AT" },
  "6912": { city: "Hörbranz", country: "AT" },
  "6922": { city: "Wolfurt", country: "AT" },
  "6923": { city: "Lauterach", country: "AT" },
  "6971": { city: "Hard", country: "AT" },
  "6973": { city: "Höchst", country: "AT" },
  "6974": { city: "Gaissau", country: "AT" },
  // Ski resorts in Austria
  "6580": { city: "St. Anton am Arlberg", country: "AT" },
  "6561": { city: "Ischgl", country: "AT" },
  "6563": { city: "Galtür", country: "AT" },
  "6764": { city: "Lech am Arlberg", country: "AT" },
  "6708": { city: "Brand", country: "AT" },
  "6774": { city: "Tschagguns", country: "AT" },
  "6780": { city: "Schruns", country: "AT" },

  // Germany - Near Lake Constance
  "88131": { city: "Lindau", country: "DE" },
  "88142": { city: "Wasserburg", country: "DE" },
  "88145": { city: "Hergatz", country: "DE" },
  "88239": { city: "Wangen im Allgäu", country: "DE" },
  "78462": { city: "Konstanz", country: "DE" },
  "78464": { city: "Konstanz", country: "DE" },
  "78465": { city: "Konstanz", country: "DE" },
  "78467": { city: "Konstanz", country: "DE" },
  "88214": { city: "Ravensburg", country: "DE" },
  "88212": { city: "Ravensburg", country: "DE" },
  "88213": { city: "Ravensburg", country: "DE" },
  "88045": { city: "Friedrichshafen", country: "DE" },
  "88046": { city: "Friedrichshafen", country: "DE" },
  "88048": { city: "Friedrichshafen", country: "DE" },
  "78224": { city: "Singen", country: "DE" },
  // Munich
  "80331": { city: "München", country: "DE" },
  "80333": { city: "München", country: "DE" },
  "80335": { city: "München", country: "DE" },
  "80336": { city: "München", country: "DE" },
  "80337": { city: "München", country: "DE" },
  "80339": { city: "München", country: "DE" },
  "80469": { city: "München", country: "DE" },
  "80538": { city: "München", country: "DE" },
  "80634": { city: "München", country: "DE" },
  "80636": { city: "München", country: "DE" },
  "80637": { city: "München", country: "DE" },
  "80639": { city: "München", country: "DE" },
  "80687": { city: "München", country: "DE" },
  "80689": { city: "München", country: "DE" },
  "80796": { city: "München", country: "DE" },
  "80797": { city: "München", country: "DE" },
  "80798": { city: "München", country: "DE" },
  "80799": { city: "München", country: "DE" },
  "80801": { city: "München", country: "DE" },
  "80802": { city: "München", country: "DE" },
  "80803": { city: "München", country: "DE" },
  "80804": { city: "München", country: "DE" },
  "80805": { city: "München", country: "DE" },
  "80807": { city: "München", country: "DE" },
  "80809": { city: "München", country: "DE" },
  "81241": { city: "München", country: "DE" },
  "81243": { city: "München", country: "DE" },
  "81245": { city: "München", country: "DE" },
  "81247": { city: "München", country: "DE" },
  "81249": { city: "München", country: "DE" },
  // Stuttgart
  "70173": { city: "Stuttgart", country: "DE" },
  "70174": { city: "Stuttgart", country: "DE" },
  "70176": { city: "Stuttgart", country: "DE" },
  "70178": { city: "Stuttgart", country: "DE" },
  "70180": { city: "Stuttgart", country: "DE" },
  "70182": { city: "Stuttgart", country: "DE" },
  "70184": { city: "Stuttgart", country: "DE" },
  "70186": { city: "Stuttgart", country: "DE" },
  "70188": { city: "Stuttgart", country: "DE" },
  "70190": { city: "Stuttgart", country: "DE" },
  "70191": { city: "Stuttgart", country: "DE" },
  "70192": { city: "Stuttgart", country: "DE" },
  "70193": { city: "Stuttgart", country: "DE" },
  "70195": { city: "Stuttgart", country: "DE" },
  "70197": { city: "Stuttgart", country: "DE" },
  "70199": { city: "Stuttgart", country: "DE" },
};

export function lookupPlz(plz: string): PlzEntry | null {
  const trimmed = plz.trim();
  return PLZ_DATABASE[trimmed] || null;
}

export function getCountryName(code: string): string {
  const countries: Record<string, string> = {
    LI: "Liechtenstein",
    CH: "Schweiz",
    AT: "Österreich",
    DE: "Deutschland",
  };
  return countries[code] || code;
}

export function getCountryFlag(code: string): string {
  const flags: Record<string, string> = {
    LI: "🇱🇮",
    CH: "🇨🇭",
    AT: "🇦🇹",
    DE: "🇩🇪",
  };
  return flags[code] || "";
}
