/**
 * PLZ (postal code) to city lookup for Switzerland, Liechtenstein, Austria, and Germany
 */

export interface PlzEntry {
  city: string;
  country: string;
}

const PLZ_DATABASE: Record<string, PlzEntry> = {
  // Liechtenstein (all postal codes)
  "9485": { city: "Nendeln", country: "LI" },
  "9486": { city: "Schaanwald", country: "LI" },
  "9487": { city: "Gamprin-Bendern", country: "LI" },
  "9488": { city: "Schellenberg", country: "LI" },
  "9489": { city: "Schaan", country: "LI" },
  "9490": { city: "Vaduz", country: "LI" },
  "9491": { city: "Ruggell", country: "LI" },
  "9492": { city: "Eschen", country: "LI" },
  "9493": { city: "Mauren", country: "LI" },
  "9494": { city: "Schaan", country: "LI" },
  "9495": { city: "Triesen", country: "LI" },
  "9496": { city: "Balzers", country: "LI" },
  "9497": { city: "Triesenberg", country: "LI" },
  "9498": { city: "Planken", country: "LI" },
  // Malbun area
  "9497 Malbun": { city: "Malbun", country: "LI" },

  // Switzerland - Major cities and ski resorts
  "8000": { city: "Zürich", country: "CH" },
  "8001": { city: "Zürich", country: "CH" },
  "8002": { city: "Zürich", country: "CH" },
  "8003": { city: "Zürich", country: "CH" },
  "8004": { city: "Zürich", country: "CH" },
  "8005": { city: "Zürich", country: "CH" },
  "8006": { city: "Zürich", country: "CH" },
  "8008": { city: "Zürich", country: "CH" },
  "8032": { city: "Zürich", country: "CH" },
  "8037": { city: "Zürich", country: "CH" },
  "8038": { city: "Zürich", country: "CH" },
  "8041": { city: "Zürich", country: "CH" },
  "8044": { city: "Zürich", country: "CH" },
  "8045": { city: "Zürich", country: "CH" },
  "8046": { city: "Zürich", country: "CH" },
  "8047": { city: "Zürich", country: "CH" },
  "8048": { city: "Zürich", country: "CH" },
  "8049": { city: "Zürich", country: "CH" },
  "8050": { city: "Zürich", country: "CH" },
  "8051": { city: "Zürich", country: "CH" },
  "8052": { city: "Zürich", country: "CH" },
  "8053": { city: "Zürich", country: "CH" },
  "8055": { city: "Zürich", country: "CH" },
  "8057": { city: "Zürich", country: "CH" },
  "3000": { city: "Bern", country: "CH" },
  "3001": { city: "Bern", country: "CH" },
  "3004": { city: "Bern", country: "CH" },
  "3005": { city: "Bern", country: "CH" },
  "3006": { city: "Bern", country: "CH" },
  "3007": { city: "Bern", country: "CH" },
  "3008": { city: "Bern", country: "CH" },
  "3010": { city: "Bern", country: "CH" },
  "3011": { city: "Bern", country: "CH" },
  "3012": { city: "Bern", country: "CH" },
  "3013": { city: "Bern", country: "CH" },
  "3014": { city: "Bern", country: "CH" },
  "3015": { city: "Bern", country: "CH" },
  "4000": { city: "Basel", country: "CH" },
  "4001": { city: "Basel", country: "CH" },
  "4051": { city: "Basel", country: "CH" },
  "4052": { city: "Basel", country: "CH" },
  "4053": { city: "Basel", country: "CH" },
  "4054": { city: "Basel", country: "CH" },
  "4055": { city: "Basel", country: "CH" },
  "4056": { city: "Basel", country: "CH" },
  "4057": { city: "Basel", country: "CH" },
  "4058": { city: "Basel", country: "CH" },
  "1200": { city: "Genève", country: "CH" },
  "1201": { city: "Genève", country: "CH" },
  "1202": { city: "Genève", country: "CH" },
  "1203": { city: "Genève", country: "CH" },
  "1204": { city: "Genève", country: "CH" },
  "1205": { city: "Genève", country: "CH" },
  "1206": { city: "Genève", country: "CH" },
  "1207": { city: "Genève", country: "CH" },
  "1208": { city: "Genève", country: "CH" },
  "1209": { city: "Genève", country: "CH" },
  "6900": { city: "Lugano", country: "CH" },
  "6901": { city: "Lugano", country: "CH" },
  "6902": { city: "Lugano", country: "CH" },
  "6903": { city: "Lugano", country: "CH" },
  "9000": { city: "St. Gallen", country: "CH" },
  "9001": { city: "St. Gallen", country: "CH" },
  "9004": { city: "St. Gallen", country: "CH" },
  "9006": { city: "St. Gallen", country: "CH" },
  "9007": { city: "St. Gallen", country: "CH" },
  "9008": { city: "St. Gallen", country: "CH" },
  "9010": { city: "St. Gallen", country: "CH" },
  "9011": { city: "St. Gallen", country: "CH" },
  "9012": { city: "St. Gallen", country: "CH" },
  "9014": { city: "St. Gallen", country: "CH" },
  "9015": { city: "St. Gallen", country: "CH" },
  "9016": { city: "St. Gallen", country: "CH" },
  "7000": { city: "Chur", country: "CH" },
  "7001": { city: "Chur", country: "CH" },
  "7002": { city: "Chur", country: "CH" },
  "7004": { city: "Chur", country: "CH" },
  "7007": { city: "Chur", country: "CH" },
  // Ski resorts
  "7500": { city: "St. Moritz", country: "CH" },
  "7270": { city: "Davos Platz", country: "CH" },
  "7260": { city: "Davos Dorf", country: "CH" },
  "3920": { city: "Zermatt", country: "CH" },
  "6390": { city: "Engelberg", country: "CH" },
  "3800": { city: "Interlaken", country: "CH" },
  "3818": { city: "Grindelwald", country: "CH" },
  "3823": { city: "Wengen", country: "CH" },
  "3825": { city: "Mürren", country: "CH" },
  "3780": { city: "Gstaad", country: "CH" },
  "3906": { city: "Saas-Fee", country: "CH" },
  "1936": { city: "Verbier", country: "CH" },
  "3963": { city: "Crans-Montana", country: "CH" },
  "7050": { city: "Arosa", country: "CH" },
  "7250": { city: "Klosters", country: "CH" },
  "7017": { city: "Flims Dorf", country: "CH" },
  "7018": { city: "Flims Waldhaus", country: "CH" },
  "7031": { city: "Laax", country: "CH" },
  "7032": { city: "Laax GR", country: "CH" },
  "7514": { city: "Ftan", country: "CH" },
  "7550": { city: "Scuol", country: "CH" },
  "7563": { city: "Samnaun", country: "CH" },
  "6460": { city: "Altdorf", country: "CH" },
  "6490": { city: "Andermatt", country: "CH" },
  // Near Liechtenstein
  "9470": { city: "Buchs SG", country: "CH" },
  "9471": { city: "Buchs SG", country: "CH" },
  "9472": { city: "Grabs", country: "CH" },
  "9473": { city: "Gams", country: "CH" },
  "9475": { city: "Sevelen", country: "CH" },
  "9476": { city: "Weite", country: "CH" },
  "9477": { city: "Trübbach", country: "CH" },
  "9478": { city: "Azmoos", country: "CH" },
  "9479": { city: "Oberschan", country: "CH" },
  "9450": { city: "Altstätten", country: "CH" },
  "9451": { city: "Kriessern", country: "CH" },
  "9452": { city: "Hinterforst", country: "CH" },
  "9453": { city: "Eichberg", country: "CH" },
  "9463": { city: "Oberriet SG", country: "CH" },
  "9464": { city: "Rüthi SG", country: "CH" },
  "9466": { city: "Sennwald", country: "CH" },
  "9467": { city: "Frümsen", country: "CH" },
  "9468": { city: "Sax", country: "CH" },
  "9469": { city: "Haag SG", country: "CH" },
  // Lucerne region
  "6000": { city: "Luzern", country: "CH" },
  "6002": { city: "Luzern", country: "CH" },
  "6003": { city: "Luzern", country: "CH" },
  "6004": { city: "Luzern", country: "CH" },
  "6005": { city: "Luzern", country: "CH" },
  "6006": { city: "Luzern", country: "CH" },
  "6010": { city: "Kriens", country: "CH" },
  "6014": { city: "Luzern", country: "CH" },
  // Winterthur
  "8400": { city: "Winterthur", country: "CH" },
  "8401": { city: "Winterthur", country: "CH" },
  "8402": { city: "Winterthur", country: "CH" },
  "8404": { city: "Winterthur", country: "CH" },
  "8405": { city: "Winterthur", country: "CH" },
  "8406": { city: "Winterthur", country: "CH" },
  "8408": { city: "Winterthur", country: "CH" },
  "8409": { city: "Winterthur", country: "CH" },

  // Lausanne
  "1000": { city: "Lausanne", country: "CH" },
  "1003": { city: "Lausanne", country: "CH" },
  "1004": { city: "Lausanne", country: "CH" },
  "1005": { city: "Lausanne", country: "CH" },
  "1006": { city: "Lausanne", country: "CH" },
  "1007": { city: "Lausanne", country: "CH" },
  "1008": { city: "Prilly", country: "CH" },
  "1009": { city: "Pully", country: "CH" },
  "1010": { city: "Lausanne", country: "CH" },
  "1011": { city: "Lausanne", country: "CH" },
  "1012": { city: "Lausanne", country: "CH" },
  "1014": { city: "Lausanne", country: "CH" },
  "1015": { city: "Lausanne", country: "CH" },
  "1018": { city: "Lausanne", country: "CH" },
  "1020": { city: "Renens", country: "CH" },
  "1022": { city: "Chavannes-près-Renens", country: "CH" },
  "1023": { city: "Crissier", country: "CH" },
  "1024": { city: "Ecublens", country: "CH" },
  "1025": { city: "St-Sulpice", country: "CH" },
  "1026": { city: "Denges", country: "CH" },
  "1027": { city: "Lonay", country: "CH" },
  "1028": { city: "Préverenges", country: "CH" },
  "1029": { city: "Villars-Ste-Croix", country: "CH" },
  "1030": { city: "Bussigny", country: "CH" },

  // Biel/Bienne
  "2500": { city: "Biel/Bienne", country: "CH" },
  "2501": { city: "Biel/Bienne", country: "CH" },
  "2502": { city: "Biel/Bienne", country: "CH" },
  "2503": { city: "Biel/Bienne", country: "CH" },
  "2504": { city: "Biel/Bienne", country: "CH" },
  "2505": { city: "Biel/Bienne", country: "CH" },
  "2512": { city: "Tüscherz-Alfermée", country: "CH" },
  "2513": { city: "Twann", country: "CH" },
  "2514": { city: "Ligerz", country: "CH" },
  "2515": { city: "Prêles", country: "CH" },
  "2516": { city: "Lamboing", country: "CH" },
  "2517": { city: "Diesse", country: "CH" },
  "2518": { city: "Nods", country: "CH" },
  "2520": { city: "La Neuveville", country: "CH" },

  // Thun
  "3600": { city: "Thun", country: "CH" },
  "3602": { city: "Thun", country: "CH" },
  "3603": { city: "Thun", country: "CH" },
  "3604": { city: "Thun", country: "CH" },
  "3607": { city: "Thun", country: "CH" },
  "3608": { city: "Thun", country: "CH" },
  "3609": { city: "Thun", country: "CH" },
  "3612": { city: "Steffisburg", country: "CH" },
  "3613": { city: "Steffisburg", country: "CH" },
  "3614": { city: "Unterlangenegg", country: "CH" },
  "3615": { city: "Heimenschwand", country: "CH" },
  "3616": { city: "Schwarzenegg", country: "CH" },
  "3617": { city: "Fahrni", country: "CH" },
  "3618": { city: "Süderen", country: "CH" },
  "3619": { city: "Eriz", country: "CH" },
  "3620": { city: "Spiez", country: "CH" },
  "3621": { city: "Faulensee", country: "CH" },
  "3622": { city: "Homberg", country: "CH" },
  "3623": { city: "Teuffenthal", country: "CH" },
  "3624": { city: "Goldiwil", country: "CH" },
  "3625": { city: "Heiligenschwendi", country: "CH" },
  "3626": { city: "Hünibach", country: "CH" },
  "3627": { city: "Heimberg", country: "CH" },
  "3628": { city: "Uttigen", country: "CH" },
  "3629": { city: "Kiesen", country: "CH" },
  "3631": { city: "Höfen", country: "CH" },
  "3632": { city: "Oberstocken", country: "CH" },
  "3633": { city: "Amsoldingen", country: "CH" },
  "3634": { city: "Thierachern", country: "CH" },
  "3635": { city: "Uebeschi", country: "CH" },
  "3636": { city: "Forst-Längenbühl", country: "CH" },
  "3638": { city: "Blumenstein", country: "CH" },
  "3645": { city: "Gwatt", country: "CH" },
  "3646": { city: "Einigen", country: "CH" },
  "3647": { city: "Reutigen", country: "CH" },
  "3652": { city: "Hilterfingen", country: "CH" },
  "3653": { city: "Oberhofen", country: "CH" },
  "3654": { city: "Gunten", country: "CH" },
  "3655": { city: "Sigriswil", country: "CH" },
  "3656": { city: "Tschingel ob Gunten", country: "CH" },
  "3657": { city: "Schwanden", country: "CH" },
  "3658": { city: "Merligen", country: "CH" },

  // Aarau
  "5000": { city: "Aarau", country: "CH" },
  "5001": { city: "Aarau", country: "CH" },
  "5004": { city: "Aarau", country: "CH" },
  "5012": { city: "Schönenwerd", country: "CH" },
  "5013": { city: "Niedergösgen", country: "CH" },
  "5014": { city: "Gretzenbach", country: "CH" },
  "5015": { city: "Erlinsbach SO", country: "CH" },
  "5017": { city: "Barmelweid", country: "CH" },
  "5018": { city: "Erlinsbach AG", country: "CH" },
  "5022": { city: "Rombach", country: "CH" },
  "5023": { city: "Biberstein", country: "CH" },
  "5024": { city: "Küttigen", country: "CH" },
  "5025": { city: "Asp", country: "CH" },
  "5026": { city: "Densbüren", country: "CH" },
  "5027": { city: "Herznach", country: "CH" },
  "5028": { city: "Ueken", country: "CH" },
  "5032": { city: "Aarau Rohr", country: "CH" },
  "5033": { city: "Buchs AG", country: "CH" },
  "5034": { city: "Suhr", country: "CH" },
  "5035": { city: "Unterentfelden", country: "CH" },
  "5036": { city: "Oberentfelden", country: "CH" },
  "5037": { city: "Muhen", country: "CH" },
  "5040": { city: "Schöftland", country: "CH" },

  // Solothurn
  "4500": { city: "Solothurn", country: "CH" },
  "4501": { city: "Solothurn", country: "CH" },
  "4502": { city: "Solothurn", country: "CH" },
  "4503": { city: "Solothurn", country: "CH" },
  "4512": { city: "Bellach", country: "CH" },
  "4513": { city: "Langendorf", country: "CH" },
  "4514": { city: "Lommiswil", country: "CH" },
  "4515": { city: "Oberdorf SO", country: "CH" },
  "4516": { city: "Feldbrunnen-St. Niklaus", country: "CH" },
  "4522": { city: "Rüttenen", country: "CH" },
  "4523": { city: "Niederwil SO", country: "CH" },
  "4524": { city: "Günsberg", country: "CH" },
  "4525": { city: "Balm bei Günsberg", country: "CH" },

  // Fribourg/Freiburg
  "1700": { city: "Fribourg", country: "CH" },
  "1701": { city: "Fribourg", country: "CH" },
  "1702": { city: "Fribourg", country: "CH" },
  "1705": { city: "Fribourg", country: "CH" },
  "1706": { city: "Fribourg", country: "CH" },
  "1707": { city: "Fribourg", country: "CH" },
  "1708": { city: "Fribourg", country: "CH" },
  "1709": { city: "Fribourg", country: "CH" },
  "1712": { city: "Tafers", country: "CH" },
  "1713": { city: "St. Antoni", country: "CH" },
  "1714": { city: "Heitenried", country: "CH" },
  "1715": { city: "Alterswil FR", country: "CH" },
  "1716": { city: "Plaffeien", country: "CH" },
  "1717": { city: "St. Ursen", country: "CH" },
  "1718": { city: "Rechthalten", country: "CH" },
  "1719": { city: "Brünisried", country: "CH" },
  "1720": { city: "Corminboeuf", country: "CH" },
  "1721": { city: "Misery-Courtion", country: "CH" },
  "1722": { city: "Bourguillon", country: "CH" },
  "1723": { city: "Marly", country: "CH" },
  "1724": { city: "Le Mouret", country: "CH" },
  "1725": { city: "Posieux", country: "CH" },
  "1726": { city: "Farvagny", country: "CH" },
  "1727": { city: "Corpataux-Magnedens", country: "CH" },
  "1728": { city: "Rossens FR", country: "CH" },

  // Neuchâtel
  "2000": { city: "Neuchâtel", country: "CH" },
  "2001": { city: "Neuchâtel", country: "CH" },
  "2002": { city: "Neuchâtel", country: "CH" },
  "2003": { city: "Neuchâtel", country: "CH" },
  "2004": { city: "Neuchâtel", country: "CH" },
  "2006": { city: "Neuchâtel", country: "CH" },
  "2007": { city: "Neuchâtel", country: "CH" },
  "2008": { city: "Neuchâtel", country: "CH" },
  "2009": { city: "Neuchâtel", country: "CH" },
  "2010": { city: "Neuchâtel", country: "CH" },
  "2012": { city: "Auvernier", country: "CH" },
  "2013": { city: "Colombier NE", country: "CH" },
  "2014": { city: "Bôle", country: "CH" },
  "2015": { city: "Areuse", country: "CH" },
  "2016": { city: "Cortaillod", country: "CH" },
  "2017": { city: "Boudry", country: "CH" },
  "2019": { city: "Chambrelien", country: "CH" },
  "2022": { city: "Bevaix", country: "CH" },
  "2023": { city: "Gorgier", country: "CH" },
  "2024": { city: "St-Aubin-Sauges", country: "CH" },
  "2025": { city: "Chez-le-Bart", country: "CH" },
  "2027": { city: "Fresens", country: "CH" },
  "2028": { city: "Vaumarcus", country: "CH" },

  // Sion/Sitten
  "1950": { city: "Sion", country: "CH" },
  "1951": { city: "Sion", country: "CH" },
  "1952": { city: "Sion", country: "CH" },
  "1953": { city: "Sion", country: "CH" },
  "1957": { city: "Ardon", country: "CH" },
  "1958": { city: "Uvrier", country: "CH" },
  "1961": { city: "Vex", country: "CH" },
  "1962": { city: "Pont-de-la-Morge", country: "CH" },
  "1963": { city: "Vétroz", country: "CH" },
  "1964": { city: "Conthey", country: "CH" },
  "1965": { city: "Savièse", country: "CH" },
  "1966": { city: "Ayent", country: "CH" },
  "1967": { city: "Bramois", country: "CH" },
  "1968": { city: "Mase", country: "CH" },
  "1969": { city: "St-Martin VS", country: "CH" },

  // La Chaux-de-Fonds
  "2300": { city: "La Chaux-de-Fonds", country: "CH" },
  "2301": { city: "La Chaux-de-Fonds", country: "CH" },
  "2302": { city: "La Chaux-de-Fonds", country: "CH" },
  "2303": { city: "La Chaux-de-Fonds", country: "CH" },
  "2304": { city: "La Chaux-de-Fonds", country: "CH" },
  "2314": { city: "La Sagne NE", country: "CH" },
  "2316": { city: "Les Ponts-de-Martel", country: "CH" },
  "2318": { city: "Brot-Plamboz", country: "CH" },
  "2322": { city: "Le Crêt-du-Locle", country: "CH" },
  "2325": { city: "Les Planchettes", country: "CH" },

  // Le Locle
  "2400": { city: "Le Locle", country: "CH" },
  "2405": { city: "La Chaux-du-Milieu", country: "CH" },
  "2406": { city: "Les Brenets", country: "CH" },
  "2414": { city: "Le Cerneux-Péquignot", country: "CH" },
  "2416": { city: "Les Brenets", country: "CH" },

  // Montreux / Vevey
  "1800": { city: "Vevey", country: "CH" },
  "1801": { city: "Le Mont-Pèlerin", country: "CH" },
  "1802": { city: "Corseaux", country: "CH" },
  "1803": { city: "Chardonne", country: "CH" },
  "1804": { city: "Corsier-sur-Vevey", country: "CH" },
  "1805": { city: "Jongny", country: "CH" },
  "1806": { city: "St-Légier-La Chiésaz", country: "CH" },
  "1807": { city: "Blonay", country: "CH" },
  "1808": { city: "Les Monts-de-Corsier", country: "CH" },
  "1809": { city: "Fenil-sur-Corsier", country: "CH" },
  "1814": { city: "La Tour-de-Peilz", country: "CH" },
  "1815": { city: "Clarens", country: "CH" },
  "1816": { city: "Chailly-Montreux", country: "CH" },
  "1817": { city: "Brent", country: "CH" },
  "1820": { city: "Montreux", country: "CH" },
  "1822": { city: "Chernex", country: "CH" },
  "1823": { city: "Glion", country: "CH" },
  "1824": { city: "Caux", country: "CH" },
  "1832": { city: "Chamby", country: "CH" },
  "1833": { city: "Les Avants", country: "CH" },

  // Yverdon-les-Bains
  "1400": { city: "Yverdon-les-Bains", country: "CH" },
  "1401": { city: "Yverdon-les-Bains", country: "CH" },
  "1404": { city: "Villars-Epeney", country: "CH" },
  "1405": { city: "Pomy", country: "CH" },
  "1406": { city: "Cronay", country: "CH" },
  "1407": { city: "Donneloye", country: "CH" },
  "1408": { city: "Prahins", country: "CH" },
  "1409": { city: "Chanéaz", country: "CH" },
  "1410": { city: "Thierrens", country: "CH" },
  "1412": { city: "Ursins", country: "CH" },
  "1413": { city: "Orzens", country: "CH" },
  "1414": { city: "Bioley-Magnoux", country: "CH" },
  "1415": { city: "Démoret", country: "CH" },
  "1416": { city: "Pailly", country: "CH" },
  "1417": { city: "Essertines-sur-Yverdon", country: "CH" },
  "1418": { city: "Vuarrens", country: "CH" },
  "1420": { city: "Fiez", country: "CH" },

  // Nyon / Morges
  "1260": { city: "Nyon", country: "CH" },
  "1261": { city: "Longirod", country: "CH" },
  "1262": { city: "Eysins", country: "CH" },
  "1263": { city: "Crassier", country: "CH" },
  "1264": { city: "St-Cergue", country: "CH" },
  "1265": { city: "La Cure", country: "CH" },
  "1266": { city: "Duillier", country: "CH" },
  "1267": { city: "Coinsins", country: "CH" },
  "1268": { city: "Burtigny", country: "CH" },
  "1269": { city: "Bassins", country: "CH" },
  "1270": { city: "Trélex", country: "CH" },
  "1271": { city: "Givrins", country: "CH" },
  "1272": { city: "Genolier", country: "CH" },
  "1273": { city: "Arzier-Le Muids", country: "CH" },
  "1274": { city: "Grens", country: "CH" },
  "1275": { city: "Chéserex", country: "CH" },
  "1276": { city: "Gingins", country: "CH" },
  "1277": { city: "Borex", country: "CH" },
  "1278": { city: "La Rippe", country: "CH" },
  "1279": { city: "Chavannes-de-Bogis", country: "CH" },
  "1100": { city: "Morges", country: "CH" },
  "1110": { city: "Morges", country: "CH" },
  "1112": { city: "Echichens", country: "CH" },
  "1113": { city: "St-Saphorin-sur-Morges", country: "CH" },
  "1114": { city: "Colombier VD", country: "CH" },
  "1115": { city: "Vullierens", country: "CH" },
  "1116": { city: "Cottens VD", country: "CH" },
  "1117": { city: "Grancy", country: "CH" },
  "1121": { city: "Bremblens", country: "CH" },
  "1122": { city: "Romanel-sur-Morges", country: "CH" },
  "1123": { city: "Aclens", country: "CH" },
  "1124": { city: "Gollion", country: "CH" },
  "1125": { city: "Monnaz", country: "CH" },
  "1126": { city: "Vaux-sur-Morges", country: "CH" },
  "1127": { city: "Clarmont", country: "CH" },
  "1128": { city: "Reverolle", country: "CH" },

  // Baden / Brugg
  "5400": { city: "Baden", country: "CH" },
  "5401": { city: "Baden", country: "CH" },
  "5402": { city: "Baden", country: "CH" },
  "5404": { city: "Baden", country: "CH" },
  "5405": { city: "Dättwil AG", country: "CH" },
  "5406": { city: "Rütihof", country: "CH" },
  "5408": { city: "Ennetbaden", country: "CH" },
  "5412": { city: "Gebenstorf", country: "CH" },
  "5413": { city: "Birmenstorf AG", country: "CH" },
  "5415": { city: "Nussbaumen AG", country: "CH" },
  "5416": { city: "Kirchdorf AG", country: "CH" },
  "5417": { city: "Untersiggenthal", country: "CH" },
  "5420": { city: "Ehrendingen", country: "CH" },
  "5423": { city: "Freienwil", country: "CH" },
  "5425": { city: "Schneisingen", country: "CH" },
  "5426": { city: "Lengnau AG", country: "CH" },
  "5430": { city: "Wettingen", country: "CH" },
  "5432": { city: "Neuenhof", country: "CH" },
  "5436": { city: "Würenlos", country: "CH" },
  "5442": { city: "Fislisbach", country: "CH" },
  "5443": { city: "Niederrohrdorf", country: "CH" },
  "5444": { city: "Künten", country: "CH" },
  "5200": { city: "Brugg AG", country: "CH" },
  "5201": { city: "Brugg AG", country: "CH" },
  "5210": { city: "Windisch", country: "CH" },
  "5212": { city: "Hausen AG", country: "CH" },
  "5213": { city: "Villnachern", country: "CH" },
  "5222": { city: "Umiken", country: "CH" },
  "5223": { city: "Riniken", country: "CH" },
  "5225": { city: "Bözberg", country: "CH" },
  "5232": { city: "Villigen", country: "CH" },
  "5233": { city: "Stilli", country: "CH" },
  "5234": { city: "Villigen", country: "CH" },
  "5235": { city: "Rüfenach AG", country: "CH" },
  "5236": { city: "Remigen", country: "CH" },
  "5237": { city: "Mönthal", country: "CH" },
  "5242": { city: "Lupfig", country: "CH" },
  "5243": { city: "Mülligen", country: "CH" },
  "5244": { city: "Birrhard", country: "CH" },
  "5245": { city: "Habsburg", country: "CH" },
  "5246": { city: "Scherz", country: "CH" },

  // Zug
  "6300": { city: "Zug", country: "CH" },
  "6301": { city: "Zug", country: "CH" },
  "6302": { city: "Zug", country: "CH" },
  "6303": { city: "Zug", country: "CH" },
  "6304": { city: "Zug", country: "CH" },
  "6312": { city: "Steinhausen", country: "CH" },
  "6313": { city: "Menzingen", country: "CH" },
  "6314": { city: "Unterägeri", country: "CH" },
  "6315": { city: "Oberägeri", country: "CH" },
  "6317": { city: "Oberwil bei Zug", country: "CH" },
  "6318": { city: "Walchwil", country: "CH" },
  "6319": { city: "Allenwinden", country: "CH" },
  "6330": { city: "Cham", country: "CH" },
  "6331": { city: "Hünenberg", country: "CH" },
  "6332": { city: "Hagendorn", country: "CH" },
  "6333": { city: "Hünenberg See", country: "CH" },
  "6340": { city: "Baar", country: "CH" },
  "6341": { city: "Baar", country: "CH" },
  "6343": { city: "Rotkreuz", country: "CH" },
  "6345": { city: "Neuheim", country: "CH" },
  "6349": { city: "Risch", country: "CH" },

  // Schaffhausen
  "8200": { city: "Schaffhausen", country: "CH" },
  "8201": { city: "Schaffhausen", country: "CH" },
  "8203": { city: "Schaffhausen", country: "CH" },
  "8207": { city: "Schaffhausen", country: "CH" },
  "8208": { city: "Schaffhausen", country: "CH" },
  "8212": { city: "Neuhausen am Rheinfall", country: "CH" },
  "8213": { city: "Neunkirch", country: "CH" },
  "8214": { city: "Gächlingen", country: "CH" },
  "8215": { city: "Hallau", country: "CH" },
  "8216": { city: "Oberhallau", country: "CH" },
  "8217": { city: "Wilchingen", country: "CH" },
  "8218": { city: "Osterfingen", country: "CH" },
  "8219": { city: "Trasadingen", country: "CH" },
  "8222": { city: "Beringen", country: "CH" },
  "8223": { city: "Guntmadingen", country: "CH" },
  "8224": { city: "Löhningen", country: "CH" },
  "8225": { city: "Siblingen", country: "CH" },
  "8226": { city: "Schleitheim", country: "CH" },
  "8228": { city: "Beggingen", country: "CH" },
  "8231": { city: "Hemmental", country: "CH" },
  "8232": { city: "Merishausen", country: "CH" },
  "8233": { city: "Bargen SH", country: "CH" },
  "8234": { city: "Stetten SH", country: "CH" },
  "8235": { city: "Lohn SH", country: "CH" },
  "8236": { city: "Opfertshofen SH", country: "CH" },
  "8239": { city: "Dörflingen", country: "CH" },
  "8240": { city: "Thayngen", country: "CH" },
  "8241": { city: "Barzheim", country: "CH" },
  "8242": { city: "Bibern SH", country: "CH" },
  "8243": { city: "Altdorf SH", country: "CH" },

  // Olten
  "4600": { city: "Olten", country: "CH" },
  "4601": { city: "Olten", country: "CH" },
  "4612": { city: "Wangen bei Olten", country: "CH" },
  "4613": { city: "Rickenbach SO", country: "CH" },
  "4614": { city: "Hägendorf", country: "CH" },
  "4615": { city: "Allerheiligenberg", country: "CH" },
  "4616": { city: "Kappel SO", country: "CH" },
  "4617": { city: "Gunzgen", country: "CH" },
  "4618": { city: "Boningen", country: "CH" },
  "4622": { city: "Egerkingen", country: "CH" },
  "4623": { city: "Neuendorf", country: "CH" },
  "4624": { city: "Härkingen", country: "CH" },
  "4625": { city: "Oberbuchsiten", country: "CH" },
  "4626": { city: "Niederbuchsiten", country: "CH" },
  "4628": { city: "Wolfwil", country: "CH" },
  "4629": { city: "Fulenbach", country: "CH" },
  "4632": { city: "Trimbach", country: "CH" },
  "4633": { city: "Hauenstein", country: "CH" },
  "4634": { city: "Wisen SO", country: "CH" },
  "4652": { city: "Winznau", country: "CH" },
  "4653": { city: "Obergösgen", country: "CH" },
  "4654": { city: "Lostorf", country: "CH" },
  "4655": { city: "Stüsslingen", country: "CH" },
  "4656": { city: "Starrkirch-Wil", country: "CH" },
  "4657": { city: "Dulliken", country: "CH" },
  "4658": { city: "Däniken SO", country: "CH" },

  // Schwyz / Einsiedeln
  "6430": { city: "Schwyz", country: "CH" },
  "6431": { city: "Schwyz", country: "CH" },
  "6432": { city: "Rickenbach SZ", country: "CH" },
  "6433": { city: "Stoos SZ", country: "CH" },
  "6434": { city: "Illgau", country: "CH" },
  "6436": { city: "Muotathal", country: "CH" },
  "6438": { city: "Ibach", country: "CH" },
  "6440": { city: "Brunnen", country: "CH" },
  "6441": { city: "Rütli", country: "CH" },
  "6442": { city: "Gersau", country: "CH" },
  "6443": { city: "Morschach", country: "CH" },
  "8840": { city: "Einsiedeln", country: "CH" },
  "8841": { city: "Gross", country: "CH" },
  "8843": { city: "Oberiberg", country: "CH" },
  "8844": { city: "Euthal", country: "CH" },
  "8845": { city: "Studen SZ", country: "CH" },
  "8846": { city: "Willerzell", country: "CH" },
  "8847": { city: "Egg SZ", country: "CH" },
  "8849": { city: "Alpthal", country: "CH" },

  // Austria - Vorarlberg (closest to Liechtenstein)
  "6800": { city: "Feldkirch", country: "AT" },
  "6805": { city: "Feldkirch-Gisingen", country: "AT" },
  "6806": { city: "Feldkirch-Nofels", country: "AT" },
  "6807": { city: "Feldkirch-Tosters", country: "AT" },
  "6808": { city: "Feldkirch-Levis", country: "AT" },
  "6811": { city: "Göfis", country: "AT" },
  "6812": { city: "Meiningen", country: "AT" },
  "6820": { city: "Frastanz", country: "AT" },
  "6822": { city: "Satteins", country: "AT" },
  "6824": { city: "Schlins", country: "AT" },
  "6830": { city: "Rankweil", country: "AT" },
  "6832": { city: "Sulz", country: "AT" },
  "6833": { city: "Klaus", country: "AT" },
  "6834": { city: "Röthis", country: "AT" },
  "6840": { city: "Götzis", country: "AT" },
  "6841": { city: "Mäder", country: "AT" },
  "6842": { city: "Koblach", country: "AT" },
  "6844": { city: "Altach", country: "AT" },
  "6845": { city: "Hohenems", country: "AT" },
  "6850": { city: "Dornbirn", country: "AT" },
  "6851": { city: "Dornbirn", country: "AT" },
  "6856": { city: "Schwarzach", country: "AT" },
  "6858": { city: "Bildstein", country: "AT" },
  "6861": { city: "Alberschwende", country: "AT" },
  "6863": { city: "Egg", country: "AT" },
  "6870": { city: "Bezau", country: "AT" },
  "6890": { city: "Lustenau", country: "AT" },
  // Note: 6900 conflicts with Lugano CH, using Bregenz with suffix
  "6911": { city: "Lochau", country: "AT" },
  "6912": { city: "Hörbranz", country: "AT" },
  "6922": { city: "Wolfurt", country: "AT" },
  "6923": { city: "Lauterach", country: "AT" },
  "6971": { city: "Hard", country: "AT" },
  "6973": { city: "Höchst", country: "AT" },
  "6974": { city: "Gaissau", country: "AT" },
  // Ski resorts in Austria
  "6580": { city: "St. Anton am Arlberg", country: "AT" },
  "6561": { city: "Ischgl", country: "AT" },
  "6563": { city: "Galtür", country: "AT" },
  "6764": { city: "Lech am Arlberg", country: "AT" },
  "6708": { city: "Brand", country: "AT" },
  "6774": { city: "Tschagguns", country: "AT" },
  "6780": { city: "Schruns", country: "AT" },

  // Germany - Major Cities

  // Berlin
  "10115": { city: "Berlin", country: "DE" },
  "10117": { city: "Berlin", country: "DE" },
  "10119": { city: "Berlin", country: "DE" },
  "10178": { city: "Berlin", country: "DE" },
  "10179": { city: "Berlin", country: "DE" },
  "10243": { city: "Berlin", country: "DE" },
  "10245": { city: "Berlin", country: "DE" },
  "10247": { city: "Berlin", country: "DE" },
  "10249": { city: "Berlin", country: "DE" },
  "10315": { city: "Berlin", country: "DE" },
  "10317": { city: "Berlin", country: "DE" },
  "10318": { city: "Berlin", country: "DE" },
  "10319": { city: "Berlin", country: "DE" },
  "10365": { city: "Berlin", country: "DE" },
  "10367": { city: "Berlin", country: "DE" },
  "10369": { city: "Berlin", country: "DE" },
  "10405": { city: "Berlin", country: "DE" },
  "10407": { city: "Berlin", country: "DE" },
  "10409": { city: "Berlin", country: "DE" },
  "10435": { city: "Berlin", country: "DE" },
  "10437": { city: "Berlin", country: "DE" },
  "10439": { city: "Berlin", country: "DE" },
  "10551": { city: "Berlin", country: "DE" },
  "10553": { city: "Berlin", country: "DE" },
  "10555": { city: "Berlin", country: "DE" },
  "10557": { city: "Berlin", country: "DE" },
  "10559": { city: "Berlin", country: "DE" },
  "10585": { city: "Berlin", country: "DE" },
  "10587": { city: "Berlin", country: "DE" },
  "10589": { city: "Berlin", country: "DE" },
  "10623": { city: "Berlin", country: "DE" },
  "10625": { city: "Berlin", country: "DE" },
  "10627": { city: "Berlin", country: "DE" },
  "10629": { city: "Berlin", country: "DE" },
  "10707": { city: "Berlin", country: "DE" },
  "10709": { city: "Berlin", country: "DE" },
  "10711": { city: "Berlin", country: "DE" },
  "10713": { city: "Berlin", country: "DE" },
  "10715": { city: "Berlin", country: "DE" },
  "10717": { city: "Berlin", country: "DE" },
  "10719": { city: "Berlin", country: "DE" },
  "10777": { city: "Berlin", country: "DE" },
  "10779": { city: "Berlin", country: "DE" },
  "10781": { city: "Berlin", country: "DE" },
  "10783": { city: "Berlin", country: "DE" },
  "10785": { city: "Berlin", country: "DE" },
  "10787": { city: "Berlin", country: "DE" },
  "10789": { city: "Berlin", country: "DE" },
  "10823": { city: "Berlin", country: "DE" },
  "10825": { city: "Berlin", country: "DE" },
  "10827": { city: "Berlin", country: "DE" },
  "10829": { city: "Berlin", country: "DE" },
  "12043": { city: "Berlin", country: "DE" },
  "12045": { city: "Berlin", country: "DE" },
  "12047": { city: "Berlin", country: "DE" },
  "12049": { city: "Berlin", country: "DE" },
  "12051": { city: "Berlin", country: "DE" },
  "12053": { city: "Berlin", country: "DE" },
  "12055": { city: "Berlin", country: "DE" },
  "12057": { city: "Berlin", country: "DE" },
  "12059": { city: "Berlin", country: "DE" },
  "12099": { city: "Berlin", country: "DE" },
  "12101": { city: "Berlin", country: "DE" },
  "12103": { city: "Berlin", country: "DE" },
  "12105": { city: "Berlin", country: "DE" },
  "12107": { city: "Berlin", country: "DE" },
  "12109": { city: "Berlin", country: "DE" },
  "12157": { city: "Berlin", country: "DE" },
  "12159": { city: "Berlin", country: "DE" },
  "12161": { city: "Berlin", country: "DE" },
  "12163": { city: "Berlin", country: "DE" },
  "12165": { city: "Berlin", country: "DE" },
  "12167": { city: "Berlin", country: "DE" },
  "12169": { city: "Berlin", country: "DE" },
  "13051": { city: "Berlin", country: "DE" },
  "13053": { city: "Berlin", country: "DE" },
  "13055": { city: "Berlin", country: "DE" },
  "13057": { city: "Berlin", country: "DE" },
  "13059": { city: "Berlin", country: "DE" },
  "13086": { city: "Berlin", country: "DE" },
  "13088": { city: "Berlin", country: "DE" },
  "13089": { city: "Berlin", country: "DE" },
  "13156": { city: "Berlin", country: "DE" },
  "13158": { city: "Berlin", country: "DE" },
  "13159": { city: "Berlin", country: "DE" },
  "13187": { city: "Berlin", country: "DE" },
  "13189": { city: "Berlin", country: "DE" },
  "14050": { city: "Berlin", country: "DE" },
  "14052": { city: "Berlin", country: "DE" },
  "14053": { city: "Berlin", country: "DE" },
  "14055": { city: "Berlin", country: "DE" },
  "14057": { city: "Berlin", country: "DE" },
  "14059": { city: "Berlin", country: "DE" },
  "14109": { city: "Berlin", country: "DE" },
  "14129": { city: "Berlin", country: "DE" },
  "14163": { city: "Berlin", country: "DE" },
  "14165": { city: "Berlin", country: "DE" },
  "14167": { city: "Berlin", country: "DE" },
  "14169": { city: "Berlin", country: "DE" },
  "14193": { city: "Berlin", country: "DE" },
  "14195": { city: "Berlin", country: "DE" },
  "14197": { city: "Berlin", country: "DE" },
  "14199": { city: "Berlin", country: "DE" },

  // Hamburg
  "20095": { city: "Hamburg", country: "DE" },
  "20097": { city: "Hamburg", country: "DE" },
  "20099": { city: "Hamburg", country: "DE" },
  "20144": { city: "Hamburg", country: "DE" },
  "20146": { city: "Hamburg", country: "DE" },
  "20148": { city: "Hamburg", country: "DE" },
  "20149": { city: "Hamburg", country: "DE" },
  "20249": { city: "Hamburg", country: "DE" },
  "20251": { city: "Hamburg", country: "DE" },
  "20253": { city: "Hamburg", country: "DE" },
  "20255": { city: "Hamburg", country: "DE" },
  "20257": { city: "Hamburg", country: "DE" },
  "20259": { city: "Hamburg", country: "DE" },
  "20354": { city: "Hamburg", country: "DE" },
  "20355": { city: "Hamburg", country: "DE" },
  "20357": { city: "Hamburg", country: "DE" },
  "20359": { city: "Hamburg", country: "DE" },
  "20457": { city: "Hamburg", country: "DE" },
  "20459": { city: "Hamburg", country: "DE" },
  "20535": { city: "Hamburg", country: "DE" },
  "20537": { city: "Hamburg", country: "DE" },
  "20539": { city: "Hamburg", country: "DE" },
  "21029": { city: "Hamburg", country: "DE" },
  "21031": { city: "Hamburg", country: "DE" },
  "21033": { city: "Hamburg", country: "DE" },
  "21035": { city: "Hamburg", country: "DE" },
  "21037": { city: "Hamburg", country: "DE" },
  "21039": { city: "Hamburg", country: "DE" },
  "21073": { city: "Hamburg", country: "DE" },
  "21075": { city: "Hamburg", country: "DE" },
  "21077": { city: "Hamburg", country: "DE" },
  "21079": { city: "Hamburg", country: "DE" },
  "21107": { city: "Hamburg", country: "DE" },
  "21109": { city: "Hamburg", country: "DE" },
  "22041": { city: "Hamburg", country: "DE" },
  "22043": { city: "Hamburg", country: "DE" },
  "22045": { city: "Hamburg", country: "DE" },
  "22047": { city: "Hamburg", country: "DE" },
  "22049": { city: "Hamburg", country: "DE" },
  "22081": { city: "Hamburg", country: "DE" },
  "22083": { city: "Hamburg", country: "DE" },
  "22085": { city: "Hamburg", country: "DE" },
  "22087": { city: "Hamburg", country: "DE" },
  "22089": { city: "Hamburg", country: "DE" },

  // Frankfurt am Main
  "60306": { city: "Frankfurt am Main", country: "DE" },
  "60308": { city: "Frankfurt am Main", country: "DE" },
  "60310": { city: "Frankfurt am Main", country: "DE" },
  "60311": { city: "Frankfurt am Main", country: "DE" },
  "60313": { city: "Frankfurt am Main", country: "DE" },
  "60314": { city: "Frankfurt am Main", country: "DE" },
  "60316": { city: "Frankfurt am Main", country: "DE" },
  "60318": { city: "Frankfurt am Main", country: "DE" },
  "60320": { city: "Frankfurt am Main", country: "DE" },
  "60322": { city: "Frankfurt am Main", country: "DE" },
  "60323": { city: "Frankfurt am Main", country: "DE" },
  "60325": { city: "Frankfurt am Main", country: "DE" },
  "60326": { city: "Frankfurt am Main", country: "DE" },
  "60327": { city: "Frankfurt am Main", country: "DE" },
  "60329": { city: "Frankfurt am Main", country: "DE" },
  "60385": { city: "Frankfurt am Main", country: "DE" },
  "60386": { city: "Frankfurt am Main", country: "DE" },
  "60388": { city: "Frankfurt am Main", country: "DE" },
  "60389": { city: "Frankfurt am Main", country: "DE" },
  "60431": { city: "Frankfurt am Main", country: "DE" },
  "60433": { city: "Frankfurt am Main", country: "DE" },
  "60435": { city: "Frankfurt am Main", country: "DE" },
  "60437": { city: "Frankfurt am Main", country: "DE" },
  "60438": { city: "Frankfurt am Main", country: "DE" },
  "60439": { city: "Frankfurt am Main", country: "DE" },
  "60486": { city: "Frankfurt am Main", country: "DE" },
  "60487": { city: "Frankfurt am Main", country: "DE" },
  "60488": { city: "Frankfurt am Main", country: "DE" },
  "60489": { city: "Frankfurt am Main", country: "DE" },
  "60528": { city: "Frankfurt am Main", country: "DE" },
  "60529": { city: "Frankfurt am Main", country: "DE" },
  "60549": { city: "Frankfurt am Main", country: "DE" },
  "60594": { city: "Frankfurt am Main", country: "DE" },
  "60596": { city: "Frankfurt am Main", country: "DE" },
  "60598": { city: "Frankfurt am Main", country: "DE" },
  "60599": { city: "Frankfurt am Main", country: "DE" },

  // Köln
  "50667": { city: "Köln", country: "DE" },
  "50668": { city: "Köln", country: "DE" },
  "50670": { city: "Köln", country: "DE" },
  "50672": { city: "Köln", country: "DE" },
  "50674": { city: "Köln", country: "DE" },
  "50676": { city: "Köln", country: "DE" },
  "50677": { city: "Köln", country: "DE" },
  "50678": { city: "Köln", country: "DE" },
  "50679": { city: "Köln", country: "DE" },
  "50733": { city: "Köln", country: "DE" },
  "50735": { city: "Köln", country: "DE" },
  "50737": { city: "Köln", country: "DE" },
  "50739": { city: "Köln", country: "DE" },
  "50765": { city: "Köln", country: "DE" },
  "50767": { city: "Köln", country: "DE" },
  "50769": { city: "Köln", country: "DE" },
  "50823": { city: "Köln", country: "DE" },
  "50825": { city: "Köln", country: "DE" },
  "50827": { city: "Köln", country: "DE" },
  "50829": { city: "Köln", country: "DE" },
  "50858": { city: "Köln", country: "DE" },
  "50859": { city: "Köln", country: "DE" },
  "50933": { city: "Köln", country: "DE" },
  "50935": { city: "Köln", country: "DE" },
  "50937": { city: "Köln", country: "DE" },
  "50939": { city: "Köln", country: "DE" },
  "50968": { city: "Köln", country: "DE" },
  "50969": { city: "Köln", country: "DE" },
  "51065": { city: "Köln", country: "DE" },
  "51067": { city: "Köln", country: "DE" },
  "51069": { city: "Köln", country: "DE" },
  "51103": { city: "Köln", country: "DE" },
  "51105": { city: "Köln", country: "DE" },
  "51107": { city: "Köln", country: "DE" },

  // Düsseldorf
  "40210": { city: "Düsseldorf", country: "DE" },
  "40211": { city: "Düsseldorf", country: "DE" },
  "40212": { city: "Düsseldorf", country: "DE" },
  "40213": { city: "Düsseldorf", country: "DE" },
  "40215": { city: "Düsseldorf", country: "DE" },
  "40217": { city: "Düsseldorf", country: "DE" },
  "40219": { city: "Düsseldorf", country: "DE" },
  "40221": { city: "Düsseldorf", country: "DE" },
  "40223": { city: "Düsseldorf", country: "DE" },
  "40225": { city: "Düsseldorf", country: "DE" },
  "40227": { city: "Düsseldorf", country: "DE" },
  "40229": { city: "Düsseldorf", country: "DE" },
  "40231": { city: "Düsseldorf", country: "DE" },
  "40233": { city: "Düsseldorf", country: "DE" },
  "40235": { city: "Düsseldorf", country: "DE" },
  "40237": { city: "Düsseldorf", country: "DE" },
  "40239": { city: "Düsseldorf", country: "DE" },
  "40468": { city: "Düsseldorf", country: "DE" },
  "40470": { city: "Düsseldorf", country: "DE" },
  "40472": { city: "Düsseldorf", country: "DE" },
  "40474": { city: "Düsseldorf", country: "DE" },
  "40476": { city: "Düsseldorf", country: "DE" },
  "40477": { city: "Düsseldorf", country: "DE" },
  "40479": { city: "Düsseldorf", country: "DE" },
  "40489": { city: "Düsseldorf", country: "DE" },
  "40545": { city: "Düsseldorf", country: "DE" },
  "40547": { city: "Düsseldorf", country: "DE" },
  "40549": { city: "Düsseldorf", country: "DE" },
  "40589": { city: "Düsseldorf", country: "DE" },
  "40591": { city: "Düsseldorf", country: "DE" },
  "40593": { city: "Düsseldorf", country: "DE" },
  "40595": { city: "Düsseldorf", country: "DE" },
  "40597": { city: "Düsseldorf", country: "DE" },
  "40599": { city: "Düsseldorf", country: "DE" },

  // Hannover
  "30159": { city: "Hannover", country: "DE" },
  "30161": { city: "Hannover", country: "DE" },
  "30163": { city: "Hannover", country: "DE" },
  "30165": { city: "Hannover", country: "DE" },
  "30167": { city: "Hannover", country: "DE" },
  "30169": { city: "Hannover", country: "DE" },
  "30171": { city: "Hannover", country: "DE" },
  "30173": { city: "Hannover", country: "DE" },
  "30175": { city: "Hannover", country: "DE" },
  "30177": { city: "Hannover", country: "DE" },
  "30179": { city: "Hannover", country: "DE" },
  "30419": { city: "Hannover", country: "DE" },
  "30449": { city: "Hannover", country: "DE" },
  "30451": { city: "Hannover", country: "DE" },
  "30453": { city: "Hannover", country: "DE" },
  "30455": { city: "Hannover", country: "DE" },
  "30457": { city: "Hannover", country: "DE" },
  "30459": { city: "Hannover", country: "DE" },
  "30519": { city: "Hannover", country: "DE" },
  "30521": { city: "Hannover", country: "DE" },
  "30539": { city: "Hannover", country: "DE" },
  "30559": { city: "Hannover", country: "DE" },
  "30625": { city: "Hannover", country: "DE" },
  "30627": { city: "Hannover", country: "DE" },
  "30629": { city: "Hannover", country: "DE" },
  "30655": { city: "Hannover", country: "DE" },
  "30657": { city: "Hannover", country: "DE" },
  "30659": { city: "Hannover", country: "DE" },

  // Nürnberg
  "90402": { city: "Nürnberg", country: "DE" },
  "90403": { city: "Nürnberg", country: "DE" },
  "90408": { city: "Nürnberg", country: "DE" },
  "90409": { city: "Nürnberg", country: "DE" },
  "90411": { city: "Nürnberg", country: "DE" },
  "90419": { city: "Nürnberg", country: "DE" },
  "90425": { city: "Nürnberg", country: "DE" },
  "90427": { city: "Nürnberg", country: "DE" },
  "90429": { city: "Nürnberg", country: "DE" },
  "90431": { city: "Nürnberg", country: "DE" },
  "90439": { city: "Nürnberg", country: "DE" },
  "90441": { city: "Nürnberg", country: "DE" },
  "90443": { city: "Nürnberg", country: "DE" },
  "90449": { city: "Nürnberg", country: "DE" },
  "90451": { city: "Nürnberg", country: "DE" },
  "90453": { city: "Nürnberg", country: "DE" },
  "90455": { city: "Nürnberg", country: "DE" },
  "90457": { city: "Nürnberg", country: "DE" },
  "90459": { city: "Nürnberg", country: "DE" },
  "90461": { city: "Nürnberg", country: "DE" },
  "90469": { city: "Nürnberg", country: "DE" },
  "90471": { city: "Nürnberg", country: "DE" },
  "90473": { city: "Nürnberg", country: "DE" },
  "90475": { city: "Nürnberg", country: "DE" },
  "90478": { city: "Nürnberg", country: "DE" },
  "90480": { city: "Nürnberg", country: "DE" },
  "90482": { city: "Nürnberg", country: "DE" },
  "90489": { city: "Nürnberg", country: "DE" },
  "90491": { city: "Nürnberg", country: "DE" },

  // Leipzig
  "04103": { city: "Leipzig", country: "DE" },
  "04105": { city: "Leipzig", country: "DE" },
  "04107": { city: "Leipzig", country: "DE" },
  "04109": { city: "Leipzig", country: "DE" },
  "04129": { city: "Leipzig", country: "DE" },
  "04155": { city: "Leipzig", country: "DE" },
  "04157": { city: "Leipzig", country: "DE" },
  "04159": { city: "Leipzig", country: "DE" },
  "04177": { city: "Leipzig", country: "DE" },
  "04178": { city: "Leipzig", country: "DE" },
  "04179": { city: "Leipzig", country: "DE" },
  "04205": { city: "Leipzig", country: "DE" },
  "04207": { city: "Leipzig", country: "DE" },
  "04209": { city: "Leipzig", country: "DE" },
  "04229": { city: "Leipzig", country: "DE" },
  "04249": { city: "Leipzig", country: "DE" },
  "04275": { city: "Leipzig", country: "DE" },
  "04277": { city: "Leipzig", country: "DE" },
  "04279": { city: "Leipzig", country: "DE" },
  "04288": { city: "Leipzig", country: "DE" },
  "04289": { city: "Leipzig", country: "DE" },
  "04299": { city: "Leipzig", country: "DE" },
  "04315": { city: "Leipzig", country: "DE" },
  "04316": { city: "Leipzig", country: "DE" },
  "04317": { city: "Leipzig", country: "DE" },
  "04318": { city: "Leipzig", country: "DE" },
  "04319": { city: "Leipzig", country: "DE" },
  "04328": { city: "Leipzig", country: "DE" },
  "04329": { city: "Leipzig", country: "DE" },
  "04347": { city: "Leipzig", country: "DE" },
  "04349": { city: "Leipzig", country: "DE" },
  "04357": { city: "Leipzig", country: "DE" },

  // Dresden
  "01067": { city: "Dresden", country: "DE" },
  "01069": { city: "Dresden", country: "DE" },
  "01097": { city: "Dresden", country: "DE" },
  "01099": { city: "Dresden", country: "DE" },
  "01109": { city: "Dresden", country: "DE" },
  "01127": { city: "Dresden", country: "DE" },
  "01129": { city: "Dresden", country: "DE" },
  "01139": { city: "Dresden", country: "DE" },
  "01156": { city: "Dresden", country: "DE" },
  "01157": { city: "Dresden", country: "DE" },
  "01159": { city: "Dresden", country: "DE" },
  "01169": { city: "Dresden", country: "DE" },
  "01187": { city: "Dresden", country: "DE" },
  "01189": { city: "Dresden", country: "DE" },
  "01217": { city: "Dresden", country: "DE" },
  "01219": { city: "Dresden", country: "DE" },
  "01237": { city: "Dresden", country: "DE" },
  "01239": { city: "Dresden", country: "DE" },
  "01257": { city: "Dresden", country: "DE" },
  "01259": { city: "Dresden", country: "DE" },
  "01277": { city: "Dresden", country: "DE" },
  "01279": { city: "Dresden", country: "DE" },
  "01307": { city: "Dresden", country: "DE" },
  "01309": { city: "Dresden", country: "DE" },
  "01324": { city: "Dresden", country: "DE" },
  "01326": { city: "Dresden", country: "DE" },
  "01328": { city: "Dresden", country: "DE" },
  "01465": { city: "Dresden", country: "DE" },

  // Dortmund
  "44135": { city: "Dortmund", country: "DE" },
  "44137": { city: "Dortmund", country: "DE" },
  "44139": { city: "Dortmund", country: "DE" },
  "44141": { city: "Dortmund", country: "DE" },
  "44143": { city: "Dortmund", country: "DE" },
  "44145": { city: "Dortmund", country: "DE" },
  "44147": { city: "Dortmund", country: "DE" },
  "44149": { city: "Dortmund", country: "DE" },
  "44225": { city: "Dortmund", country: "DE" },
  "44227": { city: "Dortmund", country: "DE" },
  "44229": { city: "Dortmund", country: "DE" },
  "44263": { city: "Dortmund", country: "DE" },
  "44265": { city: "Dortmund", country: "DE" },
  "44267": { city: "Dortmund", country: "DE" },
  "44269": { city: "Dortmund", country: "DE" },
  "44287": { city: "Dortmund", country: "DE" },
  "44289": { city: "Dortmund", country: "DE" },
  "44309": { city: "Dortmund", country: "DE" },
  "44319": { city: "Dortmund", country: "DE" },
  "44328": { city: "Dortmund", country: "DE" },
  "44329": { city: "Dortmund", country: "DE" },
  "44339": { city: "Dortmund", country: "DE" },
  "44357": { city: "Dortmund", country: "DE" },
  "44359": { city: "Dortmund", country: "DE" },
  "44369": { city: "Dortmund", country: "DE" },
  "44379": { city: "Dortmund", country: "DE" },
  "44388": { city: "Dortmund", country: "DE" },

  // Essen
  "45127": { city: "Essen", country: "DE" },
  "45128": { city: "Essen", country: "DE" },
  "45130": { city: "Essen", country: "DE" },
  "45131": { city: "Essen", country: "DE" },
  "45133": { city: "Essen", country: "DE" },
  "45134": { city: "Essen", country: "DE" },
  "45136": { city: "Essen", country: "DE" },
  "45138": { city: "Essen", country: "DE" },
  "45139": { city: "Essen", country: "DE" },
  "45141": { city: "Essen", country: "DE" },
  "45143": { city: "Essen", country: "DE" },
  "45144": { city: "Essen", country: "DE" },
  "45145": { city: "Essen", country: "DE" },
  "45147": { city: "Essen", country: "DE" },
  "45149": { city: "Essen", country: "DE" },
  "45219": { city: "Essen", country: "DE" },
  "45239": { city: "Essen", country: "DE" },
  "45257": { city: "Essen", country: "DE" },
  "45259": { city: "Essen", country: "DE" },
  "45276": { city: "Essen", country: "DE" },
  "45277": { city: "Essen", country: "DE" },
  "45279": { city: "Essen", country: "DE" },
  "45289": { city: "Essen", country: "DE" },
  "45307": { city: "Essen", country: "DE" },
  "45309": { city: "Essen", country: "DE" },
  "45326": { city: "Essen", country: "DE" },
  "45327": { city: "Essen", country: "DE" },
  "45329": { city: "Essen", country: "DE" },
  "45355": { city: "Essen", country: "DE" },
  "45356": { city: "Essen", country: "DE" },
  "45357": { city: "Essen", country: "DE" },
  "45359": { city: "Essen", country: "DE" },

  // Bremen
  "28195": { city: "Bremen", country: "DE" },
  "28197": { city: "Bremen", country: "DE" },
  "28199": { city: "Bremen", country: "DE" },
  "28201": { city: "Bremen", country: "DE" },
  "28203": { city: "Bremen", country: "DE" },
  "28205": { city: "Bremen", country: "DE" },
  "28207": { city: "Bremen", country: "DE" },
  "28209": { city: "Bremen", country: "DE" },
  "28211": { city: "Bremen", country: "DE" },
  "28213": { city: "Bremen", country: "DE" },
  "28215": { city: "Bremen", country: "DE" },
  "28217": { city: "Bremen", country: "DE" },
  "28219": { city: "Bremen", country: "DE" },
  "28237": { city: "Bremen", country: "DE" },
  "28239": { city: "Bremen", country: "DE" },
  "28259": { city: "Bremen", country: "DE" },
  "28277": { city: "Bremen", country: "DE" },
  "28279": { city: "Bremen", country: "DE" },
  "28307": { city: "Bremen", country: "DE" },
  "28309": { city: "Bremen", country: "DE" },
  "28325": { city: "Bremen", country: "DE" },
  "28327": { city: "Bremen", country: "DE" },
  "28329": { city: "Bremen", country: "DE" },
  "28355": { city: "Bremen", country: "DE" },
  "28357": { city: "Bremen", country: "DE" },
  "28359": { city: "Bremen", country: "DE" },

  // München (expanded)
  "80331": { city: "München", country: "DE" },
  "80333": { city: "München", country: "DE" },
  "80335": { city: "München", country: "DE" },
  "80336": { city: "München", country: "DE" },
  "80337": { city: "München", country: "DE" },
  "80339": { city: "München", country: "DE" },
  "80469": { city: "München", country: "DE" },
  "80538": { city: "München", country: "DE" },
  "80539": { city: "München", country: "DE" },
  "80634": { city: "München", country: "DE" },
  "80636": { city: "München", country: "DE" },
  "80637": { city: "München", country: "DE" },
  "80638": { city: "München", country: "DE" },
  "80639": { city: "München", country: "DE" },
  "80686": { city: "München", country: "DE" },
  "80687": { city: "München", country: "DE" },
  "80689": { city: "München", country: "DE" },
  "80796": { city: "München", country: "DE" },
  "80797": { city: "München", country: "DE" },
  "80798": { city: "München", country: "DE" },
  "80799": { city: "München", country: "DE" },
  "80801": { city: "München", country: "DE" },
  "80802": { city: "München", country: "DE" },
  "80803": { city: "München", country: "DE" },
  "80804": { city: "München", country: "DE" },
  "80805": { city: "München", country: "DE" },
  "80807": { city: "München", country: "DE" },
  "80809": { city: "München", country: "DE" },
  "80933": { city: "München", country: "DE" },
  "80935": { city: "München", country: "DE" },
  "80939": { city: "München", country: "DE" },
  "80992": { city: "München", country: "DE" },
  "80993": { city: "München", country: "DE" },
  "80995": { city: "München", country: "DE" },
  "80997": { city: "München", country: "DE" },
  "80999": { city: "München", country: "DE" },
  "81241": { city: "München", country: "DE" },
  "81243": { city: "München", country: "DE" },
  "81245": { city: "München", country: "DE" },
  "81247": { city: "München", country: "DE" },
  "81249": { city: "München", country: "DE" },
  "81369": { city: "München", country: "DE" },
  "81371": { city: "München", country: "DE" },
  "81373": { city: "München", country: "DE" },
  "81375": { city: "München", country: "DE" },
  "81377": { city: "München", country: "DE" },
  "81379": { city: "München", country: "DE" },
  "81475": { city: "München", country: "DE" },
  "81476": { city: "München", country: "DE" },
  "81477": { city: "München", country: "DE" },
  "81479": { city: "München", country: "DE" },
  "81539": { city: "München", country: "DE" },
  "81541": { city: "München", country: "DE" },
  "81543": { city: "München", country: "DE" },
  "81545": { city: "München", country: "DE" },
  "81547": { city: "München", country: "DE" },
  "81549": { city: "München", country: "DE" },
  "81667": { city: "München", country: "DE" },
  "81669": { city: "München", country: "DE" },
  "81671": { city: "München", country: "DE" },
  "81673": { city: "München", country: "DE" },
  "81675": { city: "München", country: "DE" },
  "81677": { city: "München", country: "DE" },
  "81679": { city: "München", country: "DE" },
  "81735": { city: "München", country: "DE" },
  "81737": { city: "München", country: "DE" },
  "81739": { city: "München", country: "DE" },
  "81825": { city: "München", country: "DE" },
  "81827": { city: "München", country: "DE" },
  "81829": { city: "München", country: "DE" },

  // Stuttgart (expanded)
  "70173": { city: "Stuttgart", country: "DE" },
  "70174": { city: "Stuttgart", country: "DE" },
  "70176": { city: "Stuttgart", country: "DE" },
  "70178": { city: "Stuttgart", country: "DE" },
  "70180": { city: "Stuttgart", country: "DE" },
  "70182": { city: "Stuttgart", country: "DE" },
  "70184": { city: "Stuttgart", country: "DE" },
  "70186": { city: "Stuttgart", country: "DE" },
  "70188": { city: "Stuttgart", country: "DE" },
  "70190": { city: "Stuttgart", country: "DE" },
  "70191": { city: "Stuttgart", country: "DE" },
  "70192": { city: "Stuttgart", country: "DE" },
  "70193": { city: "Stuttgart", country: "DE" },
  "70195": { city: "Stuttgart", country: "DE" },
  "70197": { city: "Stuttgart", country: "DE" },
  "70199": { city: "Stuttgart", country: "DE" },
  "70327": { city: "Stuttgart", country: "DE" },
  "70329": { city: "Stuttgart", country: "DE" },
  "70372": { city: "Stuttgart", country: "DE" },
  "70374": { city: "Stuttgart", country: "DE" },
  "70376": { city: "Stuttgart", country: "DE" },
  "70378": { city: "Stuttgart", country: "DE" },
  "70435": { city: "Stuttgart", country: "DE" },
  "70437": { city: "Stuttgart", country: "DE" },
  "70439": { city: "Stuttgart", country: "DE" },
  "70469": { city: "Stuttgart", country: "DE" },
  "70499": { city: "Stuttgart", country: "DE" },
  "70563": { city: "Stuttgart", country: "DE" },
  "70565": { city: "Stuttgart", country: "DE" },
  "70567": { city: "Stuttgart", country: "DE" },
  "70569": { city: "Stuttgart", country: "DE" },
  "70597": { city: "Stuttgart", country: "DE" },
  "70599": { city: "Stuttgart", country: "DE" },
  "70619": { city: "Stuttgart", country: "DE" },
  "70629": { city: "Stuttgart", country: "DE" },

  // Germany - Ski Regions

  // Allgäu
  "87435": { city: "Kempten", country: "DE" },
  "87437": { city: "Kempten", country: "DE" },
  "87439": { city: "Kempten", country: "DE" },
  "87509": { city: "Immenstadt", country: "DE" },
  "87527": { city: "Sonthofen", country: "DE" },
  "87534": { city: "Oberstaufen", country: "DE" },
  "87538": { city: "Fischen im Allgäu", country: "DE" },
  "87541": { city: "Bad Hindelang", country: "DE" },
  "87544": { city: "Blaichach", country: "DE" },
  "87545": { city: "Burgberg im Allgäu", country: "DE" },
  "87547": { city: "Missen-Wilhams", country: "DE" },
  "87549": { city: "Rettenberg", country: "DE" },
  "87561": { city: "Oberstdorf", country: "DE" },
  "87629": { city: "Füssen", country: "DE" },
  "87637": { city: "Seeg", country: "DE" },
  "87639": { city: "Hopferau", country: "DE" },
  "87640": { city: "Biessenhofen", country: "DE" },
  "87642": { city: "Halblech", country: "DE" },
  "87645": { city: "Schwangau", country: "DE" },
  "87647": { city: "Unterthingau", country: "DE" },
  "87648": { city: "Aitrang", country: "DE" },
  "87650": { city: "Baisweil", country: "DE" },

  // Garmisch-Partenkirchen Area
  "82467": { city: "Garmisch-Partenkirchen", country: "DE" },
  "82475": { city: "Garmisch-Partenkirchen", country: "DE" },
  "82481": { city: "Mittenwald", country: "DE" },
  "82487": { city: "Oberammergau", country: "DE" },
  "82488": { city: "Ettal", country: "DE" },
  "82490": { city: "Farchant", country: "DE" },
  "82491": { city: "Grainau", country: "DE" },
  "82493": { city: "Krün", country: "DE" },
  "82494": { city: "Krün", country: "DE" },
  "82496": { city: "Oberau", country: "DE" },
  "82497": { city: "Unterammergau", country: "DE" },
  "82499": { city: "Wallgau", country: "DE" },

  // Berchtesgadener Land
  "83404": { city: "Ainring", country: "DE" },
  "83435": { city: "Bad Reichenhall", country: "DE" },
  "83451": { city: "Piding", country: "DE" },
  "83454": { city: "Anger", country: "DE" },
  "83457": { city: "Bayerisch Gmain", country: "DE" },
  "83458": { city: "Schneizlreuth", country: "DE" },
  "83471": { city: "Berchtesgaden", country: "DE" },
  "83483": { city: "Bischofswiesen", country: "DE" },
  "83486": { city: "Ramsau bei Berchtesgaden", country: "DE" },
  "83487": { city: "Marktschellenberg", country: "DE" },
  "83489": { city: "Strub", country: "DE" },

  // Black Forest / Schwarzwald
  "77652": { city: "Offenburg", country: "DE" },
  "77654": { city: "Offenburg", country: "DE" },
  "77656": { city: "Offenburg", country: "DE" },
  "78098": { city: "Triberg", country: "DE" },
  "78112": { city: "St. Georgen im Schwarzwald", country: "DE" },
  "78120": { city: "Furtwangen", country: "DE" },
  "78126": { city: "Königsfeld im Schwarzwald", country: "DE" },
  "78132": { city: "Hornberg", country: "DE" },
  "78136": { city: "Schonach im Schwarzwald", country: "DE" },
  "78141": { city: "Schönwald im Schwarzwald", country: "DE" },
  "79098": { city: "Freiburg im Breisgau", country: "DE" },
  "79100": { city: "Freiburg im Breisgau", country: "DE" },
  "79102": { city: "Freiburg im Breisgau", country: "DE" },
  "79104": { city: "Freiburg im Breisgau", country: "DE" },
  "79106": { city: "Freiburg im Breisgau", country: "DE" },
  "79108": { city: "Freiburg im Breisgau", country: "DE" },
  "79110": { city: "Freiburg im Breisgau", country: "DE" },
  "79111": { city: "Freiburg im Breisgau", country: "DE" },
  "79112": { city: "Freiburg im Breisgau", country: "DE" },
  "79114": { city: "Freiburg im Breisgau", country: "DE" },
  "79115": { city: "Freiburg im Breisgau", country: "DE" },
  "79117": { city: "Freiburg im Breisgau", country: "DE" },
  "79822": { city: "Titisee-Neustadt", country: "DE" },
  "79856": { city: "Hinterzarten", country: "DE" },
  "79859": { city: "Schluchsee", country: "DE" },
  "79862": { city: "Höchenschwand", country: "DE" },
  "79868": { city: "Feldberg", country: "DE" },
  "79871": { city: "Eisenbach", country: "DE" },
  "79874": { city: "Breitnau", country: "DE" },
  "79877": { city: "Friedenweiler", country: "DE" },

  // Lake Constance / Bodensee (expanded)
  "78224": { city: "Singen", country: "DE" },
  "78234": { city: "Engen", country: "DE" },
  "78247": { city: "Hilzingen", country: "DE" },
  "78315": { city: "Radolfzell", country: "DE" },
  "78333": { city: "Stockach", country: "DE" },
  "78337": { city: "Öhningen", country: "DE" },
  "78343": { city: "Gaienhofen", country: "DE" },
  "78351": { city: "Bodman-Ludwigshafen", country: "DE" },
  "78462": { city: "Konstanz", country: "DE" },
  "78464": { city: "Konstanz", country: "DE" },
  "78465": { city: "Konstanz", country: "DE" },
  "78467": { city: "Konstanz", country: "DE" },
  "78476": { city: "Allensbach", country: "DE" },
  "78479": { city: "Reichenau", country: "DE" },
  "88045": { city: "Friedrichshafen", country: "DE" },
  "88046": { city: "Friedrichshafen", country: "DE" },
  "88048": { city: "Friedrichshafen", country: "DE" },
  "88069": { city: "Tettnang", country: "DE" },
  "88079": { city: "Kressbronn", country: "DE" },
  "88085": { city: "Langenargen", country: "DE" },
  "88090": { city: "Immenstaad", country: "DE" },
  "88094": { city: "Oberteuringen", country: "DE" },
  "88097": { city: "Eriskirch", country: "DE" },
  "88131": { city: "Lindau", country: "DE" },
  "88138": { city: "Weißensberg", country: "DE" },
  "88142": { city: "Wasserburg am Bodensee", country: "DE" },
  "88145": { city: "Hergatz", country: "DE" },
  "88147": { city: "Achberg", country: "DE" },
  "88149": { city: "Nonnenhorn", country: "DE" },
  "88161": { city: "Lindenberg im Allgäu", country: "DE" },
  "88171": { city: "Weiler-Simmerberg", country: "DE" },
  "88175": { city: "Scheidegg", country: "DE" },
  "88179": { city: "Oberreute", country: "DE" },
  "88212": { city: "Ravensburg", country: "DE" },
  "88213": { city: "Ravensburg", country: "DE" },
  "88214": { city: "Ravensburg", country: "DE" },
  "88239": { city: "Wangen im Allgäu", country: "DE" },
  "88250": { city: "Weingarten", country: "DE" },
  "88255": { city: "Baienfurt", country: "DE" },
  "88260": { city: "Argenbühl", country: "DE" },
  "88263": { city: "Horgenzell", country: "DE" },
  "88267": { city: "Vogt", country: "DE" },
  "88271": { city: "Wilhelmsdorf", country: "DE" },
  "88273": { city: "Fronreute", country: "DE" },
  "88276": { city: "Berg", country: "DE" },
  "88279": { city: "Amtzell", country: "DE" },
  "88281": { city: "Schlier", country: "DE" },
  "88284": { city: "Wolpertswende", country: "DE" },
  "88285": { city: "Bodnegg", country: "DE" },
  "88287": { city: "Grünkraut", country: "DE" },
  "88289": { city: "Waldburg", country: "DE" },
  "88316": { city: "Isny im Allgäu", country: "DE" },
  "88317": { city: "Aichstetten", country: "DE" },
  "88319": { city: "Aitrach", country: "DE" },
  "88326": { city: "Aulendorf", country: "DE" },
  "88339": { city: "Bad Waldsee", country: "DE" },
  "88348": { city: "Bad Saulgau", country: "DE" },
  "88353": { city: "Kisslegg", country: "DE" },
  "88356": { city: "Ostrach", country: "DE" },
  "88361": { city: "Altshausen", country: "DE" },
  "88364": { city: "Wolfegg", country: "DE" },
  "88367": { city: "Hohentengen", country: "DE" },
  "88368": { city: "Bergatreute", country: "DE" },
  "88370": { city: "Ebenweiler", country: "DE" },
  "88371": { city: "Ebersbach-Musbach", country: "DE" },
  "88374": { city: "Hoßkirch", country: "DE" },
  "88376": { city: "Königseggwald", country: "DE" },
  "88377": { city: "Riedhausen", country: "DE" },
  "88379": { city: "Guggenhausen", country: "DE" },

  // Ulm Region
  "89073": { city: "Ulm", country: "DE" },
  "89075": { city: "Ulm", country: "DE" },
  "89077": { city: "Ulm", country: "DE" },
  "89079": { city: "Ulm", country: "DE" },
  "89081": { city: "Ulm", country: "DE" },

  // Augsburg
  "86150": { city: "Augsburg", country: "DE" },
  "86152": { city: "Augsburg", country: "DE" },
  "86153": { city: "Augsburg", country: "DE" },
  "86154": { city: "Augsburg", country: "DE" },
  "86156": { city: "Augsburg", country: "DE" },
  "86157": { city: "Augsburg", country: "DE" },
  "86159": { city: "Augsburg", country: "DE" },
  "86161": { city: "Augsburg", country: "DE" },
  "86163": { city: "Augsburg", country: "DE" },
  "86165": { city: "Augsburg", country: "DE" },
  "86167": { city: "Augsburg", country: "DE" },
  "86169": { city: "Augsburg", country: "DE" },
  "86179": { city: "Augsburg", country: "DE" },
  "86199": { city: "Augsburg", country: "DE" },
};

export function lookupPlz(plz: string): PlzEntry | null {
  const trimmed = plz.trim();
  return PLZ_DATABASE[trimmed] || null;
}

export function getCountryName(code: string): string {
  const countries: Record<string, string> = {
    LI: "Liechtenstein",
    CH: "Schweiz",
    AT: "Österreich",
    DE: "Deutschland",
  };
  return countries[code] || code;
}

export function getCountryFlag(code: string): string {
  const flags: Record<string, string> = {
    LI: "🇱🇮",
    CH: "🇨🇭",
    AT: "🇦🇹",
    DE: "🇩🇪",
  };
  return flags[code] || "";
}
